import { defineField, defineType } from 'sanity'

/**
 * Page d’accueil : groupes numérotés pour guider les éditeurs non techniques.
 */
export const homePageType = defineType({
  name: ‘homePage’,
  title: ‘🏠 Page d’accueil’,
  type: ‘document’,
  description:
    ‘👋 Bienvenue! Vous modifiez la première page que les visiteurs voient. Les changements s\’affichent après clic sur **Publier** (en haut à droite). Les photos doivent être de bonne qualité et pas coupées (format paysage préféré). Besoin d\’aide? Cliquez sur le ❓ à côté de chaque champ!’,
  groups: [
    { name: ‘hero’, title: ‘1️⃣ Vidéo + titre en haut’, default: true },
    { name: ‘carousel’, title: ‘2️⃣ Photos qui défilent’ },
    { name: ‘manifesto’, title: ‘3️⃣ Bandeau « Le corps comme… »’ },
    { name: ‘intro’, title: ‘4️⃣ Section « La compagnie »’ },
    { name: ‘imagesBloc’, title: ‘5️⃣ Encart « Photos »’ },
    { name: ‘creations’, title: ‘6️⃣ Section « Créations »’ },
  ],
  fields: [
    defineField({
      name: 'heroVideo',
      title: '🎬 Vidéo en plein écran',
      description: 'La vidéo de fond de la page d\'accueil. Formats acceptés: MP4, WebM. Conseil: moins de 50MB pour charger vite. Si pas de vidéo, une photo s\'affiche à la place.',
      type: 'file',
      options: { accept: 'video/*' },
      group: 'hero',
    }),
    defineField({
      name: 'heroTitle',
      title: 'Grand titre (ex. Cie. Horme)',
      type: 'string',
      initialValue: 'Cie. Horme',
      group: 'hero',
    }),
    defineField({
      name: 'heroLine1',
      title: 'Sous-titre — ligne 1',
      type: 'string',
      initialValue: 'Louise Melli et Joséphine Hassid-Langlois',
      group: 'hero',
    }),
    defineField({
      name: 'heroLine2',
      title: 'Sous-titre — ligne 2',
      type: 'string',
      initialValue: 'écriture chorégraphique, Paris.',
      group: 'hero',
    }),
    defineField({
      name: ‘slides’,
      title: ‘📸 Photos qui défilent (carrousel)’,
      description:
        ‘⭐ IMPORTANT: Cliquez « Ajouter » pour chaque photo. **GLISSEZ** (icône ⋮⋮ à gauche) pour changer l\’ordre. ❌ ATTENTION: Supprimer toutes les photos redonne les photos par défaut. Conseil: utiliser photos en paysage (16:9), min 1920px de large, format JPG/PNG.’,
      type: ‘array’,
      of: [{ type: ‘homeSlide’ }],
      group: ‘carousel’,
    }),
    defineField({
      name: 'manifestoLine1',
      title: '✍️ Texte avant le mot bleu',
      description: 'Ex: « Le corps comme »',
      type: 'string',
      initialValue: '',
      group: 'manifesto',
    }),
    defineField({
      name: 'manifestoAccent',
      title: '💙 Mot ou phrase en bleu',
      description: 'Ce mot/phrase s\'affiche en bleu et en gros. Ex: « langage premier »',
      type: 'string',
      initialValue: '',
      group: 'manifesto',
    }),
    defineField({
      name: 'manifestoCtaLabel',
      title: 'Texte du lien (vers la page Créations)',
      type: 'string',
      initialValue: 'Voir les créations →',
      group: 'manifesto',
    }),
    defineField({
      name: 'introKicker',
      title: '🏷️ Petit titre (surtitre)',
      type: 'string',
      initialValue: '',
      group: 'intro',
    }),
    defineField({
      name: 'introParagraph1',
      title: '📝 Texte principal',
      description: 'Le texte principal qui présente la compagnie. Peut être long (plusieurs phrases).',
      type: 'text',
      rows: 5,
      initialValue: '',
      group: 'intro',
    }),
    defineField({
      name: 'introParagraph2',
      title: '📝 Texte secondaire',
      description: 'Un texte plus court, plus léger. S\'affiche en gris clair.',
      type: 'text',
      rows: 4,
      initialValue: '',
      group: 'intro',
    }),
    defineField({
      name: 'introCtaLabel',
      title: 'Texte du lien vers Présentation',
      type: 'string',
      initialValue: 'Découvrir la compagnie →',
      group: 'intro',
    }),
    defineField({
      name: 'imagesSectionKicker',
      title: '🏷️ Titre de la section photos',
      type: 'string',
      initialValue: '',
      group: 'imagesBloc',
    }),
    defineField({
      name: 'imagesSectionBody',
      title: '📝 Description',
      description: 'Un court texte expliquant ce que le visiteur verra en cliquant.',
      type: 'text',
      rows: 3,
      initialValue: '',
      group: 'imagesBloc',
    }),
    defineField({
      name: 'imagesSectionCtaLabel',
      title: 'Texte du lien',
      type: 'string',
      initialValue: 'Présentation →',
      group: 'imagesBloc',
    }),
    defineField({
      name: 'creationsKicker',
      title: '🏷️ Titre de la section créations',
      type: 'string',
      initialValue: '',
      group: 'creations',
    }),
    defineField({
      name: 'creationsFooterCtaLabel',
      title: 'Lien du bas (« Toutes les créations »)',
      type: 'string',
      initialValue: 'Toutes les créations →',
      group: 'creations',
    }),
  ],
})
